### ISSUE TITLE
Bundle affwp-addon-tools and implement requirement checks

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/affiliatewp-leaderboard#25]
In order to facilitate enforcing [minimum dependency requirements](https://docs.affiliatewp.com/article/2361-minimum-requirements-roadmaps) going forward, we need to bundle the affwp-addon-tools package via composer and refactor the plugin bootstrap to extend the requirements class.

**Comment by dbeja** [comment]
PR: #26

**Comment by dbeja** [comment]
Merged #26 against `release/1.1`.
